repos:
- hooks:
  - id: check-merge-conflict
  - id: check-json
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 20.8b1
- hooks:
  - id: csslint
  repo: https://github.com/pre-commit/mirrors-csslint
  rev: v1.0.5
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: master
-   repo: https://github.com/PyCQA/bandit
    rev: 'master'
    hooks:
    - id: bandit