# Generated by Django 3.0.11 on 2020-12-06 01:00

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmetadata.models
import wagtailstreamforms.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("wagtail_resume", "0005_auto_20200227_1224"),
        ("wagtailimages", "0022_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumePage",
            fields=[
                (
                    "baseresumepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtail_resume.BaseResumePage",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                        verbose_name="Search image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("resume_page"),
                "wagtail_resume.baseresumepage",
                wagtailmetadata.models.MetadataMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "header",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "header",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("h1", "H1"),
                                                    ("h2", "H2"),
                                                    ("h3", "H3"),
                                                    ("h4", "H4"),
                                                    ("h5", "H5"),
                                                    ("h6", "H6"),
                                                ],
                                                label="Header Size",
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.core.blocks.CharBlock(
                                                label="Text", max_length=50
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "list",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "content",
                                            wagtail.core.blocks.ListBlock(
                                                wagtail.core.blocks.CharBlock(),
                                                label="Items",
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "image_text_overlay",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image"
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.core.blocks.CharBlock(
                                                label="Text", max_length=200
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "cropped_images_with_text",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image_items",
                                            wagtail.core.blocks.ListBlock(
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                label="Image"
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.core.blocks.CharBlock(
                                                                label="Text",
                                                                max_length=200,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                label="Image Item",
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "list_with_images",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "list_items",
                                            wagtail.core.blocks.ListBlock(
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                label="Image"
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.core.blocks.CharBlock(
                                                                label="Title",
                                                                max_length=200,
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.core.blocks.CharBlock(
                                                                label="Text",
                                                                max_length=200,
                                                            ),
                                                        ),
                                                        (
                                                            "link_text",
                                                            wagtail.core.blocks.CharBlock(
                                                                label="Link Text",
                                                                max_length=200,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "link_url",
                                                            wagtail.core.blocks.URLBlock(
                                                                label="Link URL",
                                                                max_length=200,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                label="List Item",
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "thumbnail_gallery",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image_items",
                                            wagtail.core.blocks.ListBlock(
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                label="Image"
                                                            ),
                                                        )
                                                    ]
                                                ),
                                                label="Image",
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "chart",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.core.blocks.CharBlock(
                                                default="Chart Title",
                                                label="Title",
                                                max_length=120,
                                            ),
                                        ),
                                        (
                                            "chart_type",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("bar", "Bar"),
                                                    ("horizontalBar", "Horizontal Bar"),
                                                    ("pie", "Pie"),
                                                    ("doughnut", "Doughnut"),
                                                    ("polarArea", "Polar Area"),
                                                    ("radar", "Radar"),
                                                    ("line", "Line"),
                                                ],
                                                label="Chart Type",
                                            ),
                                        ),
                                        (
                                            "labels",
                                            wagtail.core.blocks.ListBlock(
                                                wagtail.core.blocks.CharBlock(
                                                    default="Label",
                                                    label="Label",
                                                    max_length=40,
                                                ),
                                                label="Chart Labels",
                                            ),
                                        ),
                                        (
                                            "datasets",
                                            wagtail.core.blocks.ListBlock(
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "label",
                                                            wagtail.core.blocks.CharBlock(
                                                                default="Dataset #1",
                                                                label="Dataset Label",
                                                                max_length=120,
                                                            ),
                                                        ),
                                                        (
                                                            "dataset_data",
                                                            wagtail.core.blocks.ListBlock(
                                                                wagtail.core.blocks.IntegerBlock(),
                                                                default="0",
                                                                label="Data",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                label="Dataset",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "map",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "marker_title",
                                            wagtail.core.blocks.CharBlock(
                                                default="Marker Title 'This will be updated after you save changes.'",
                                                max_length=120,
                                            ),
                                        ),
                                        (
                                            "marker_description",
                                            wagtail.core.blocks.RichTextBlock(),
                                        ),
                                        (
                                            "zoom_level",
                                            wagtail.core.blocks.IntegerBlock(
                                                default="2",
                                                max_value=18,
                                                min_value=0,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "location_x",
                                            wagtail.core.blocks.FloatBlock(
                                                default="35.0", required=False
                                            ),
                                        ),
                                        (
                                            "location_y",
                                            wagtail.core.blocks.FloatBlock(
                                                default="0.16", required=False
                                            ),
                                        ),
                                        (
                                            "marker_x",
                                            wagtail.core.blocks.FloatBlock(
                                                default="51.5", required=False
                                            ),
                                        ),
                                        (
                                            "marker_y",
                                            wagtail.core.blocks.FloatBlock(
                                                default="-0.09", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "image_slider",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image_items",
                                            wagtail.core.blocks.ListBlock(
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                label="Image"
                                                            ),
                                                        )
                                                    ]
                                                ),
                                                label="Image",
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "form",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "form",
                                            wagtailstreamforms.blocks.FormChooserBlock(),
                                        ),
                                        (
                                            "form_action",
                                            wagtail.core.blocks.CharBlock(
                                                help_text='The form post action. "" or "." for the current page or a url',
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "form_reference",
                                            wagtailstreamforms.blocks.InfoBlock(
                                                help_text="This form will be given a unique reference once saved",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "Parallax",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.core.blocks.RichTextBlock(
                                                help_text="Text to overlay parallax",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "img",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="Image for parallax",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "speed",
                                            wagtail.core.blocks.FloatBlock(
                                                default=0.2,
                                                help_text="Speed to run the parallax",
                                                max_value=1.0,
                                                min_value=0.0,
                                                required=True,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "Code",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "language",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("bash", "Bash/Shell"),
                                                    ("css", "CSS"),
                                                    ("diff", "diff"),
                                                    ("html", "HTML"),
                                                    ("javascript", "Javascript"),
                                                    ("json", "JSON"),
                                                    ("python", "Python"),
                                                    ("scss", "SCSS"),
                                                    ("yaml", "YAML"),
                                                ],
                                                help_text="Coding language",
                                                identifier="language",
                                                label="Language",
                                            ),
                                        ),
                                        (
                                            "code",
                                            wagtail.core.blocks.TextBlock(
                                                identifier="code", label="Code"
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "Timeline",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "sections",
                                            wagtail.core.blocks.ListBlock(
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "blurbs",
                                                            wagtail.core.blocks.ListBlock(
                                                                wagtail.core.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "blurb_header",
                                                                            wagtail.core.blocks.CharBlock(
                                                                                required=True
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "blurb_content",
                                                                            wagtail.core.blocks.RichTextBlock(
                                                                                required=True
                                                                            ),
                                                                        ),
                                                                    ]
                                                                )
                                                            ),
                                                        )
                                                    ]
                                                )
                                            ),
                                        )
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                    ),
                ),
                ("author_twitter_handle", models.CharField(max_length=15)),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                        verbose_name="Search image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("home_page"),
                wagtailmetadata.models.MetadataMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
    ]
