# Generated by Django 3.1.2 on 2020-10-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0022_uploadedimage"),
        ("home", "0007_homepage_search_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="author_twitter_handle",
            field=models.CharField(default="ShadeKingCam", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resumepage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Search image",
            ),
        ),
    ]
